### ISSUE TITLE
[Rendering] Markdown text rendering in serif font on iOS Microsoft Teams app

### ISSUE THREAD

**Issue by khirasaki** [microsoft/Teams-AdaptiveCards-Mobile#69] opened 2023-12-21 22:55 UTC
### Target Platforms

iOS

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

I am using Adaptive Cards for my bot to communicate with a Teams user.
When I create a TextBlock that contains markdown, on the iOS app, the text gets rendered in a serif (instead of the standard sans serif font). This makes things look crazy.
Please advise on the appropriate fix or workaround.

### Screenshots

![IMG_8345](https://github.com/microsoft/AdaptiveCards/assets/1480001/633c2e4c-c3b9-4cbe-8ab3-fd754bc89c65)

### Card JSON

```JSON
Samples (sorry, pulled from log outputs):

[
  {
    type: 'TextBlock',
    wrap: true,
    text: 'Unclear project ownership can indeed lead to misunderstandings and a power struggle that escalates into a broader conflict. It may also impact team morale and clarity within roles. Other common causes of conflict could include:',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Disagreements',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Clash of personalities',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Values being questioned',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Different work styles or beliefs',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Unfairness',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Discrimination',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Poor management',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '- Difficult customers',
    spacing: 'Medium'
  }
]


[
  {
    type: 'TextBlock',
    wrap: true,
    text: '**Challenging behaviour** is conduct that disrupts other people or the work environment.',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: 'It includes aggression, non-compliance, tantrums, or verbal abuse. It is never a good thing.',
    spacing: 'Medium'
  },
  {
    type: 'TextBlock',
    wrap: true,
    text: '🤔 Reflection: Recall challenging behaviour that you observed at work. What was the situation that caused it?',
    spacing: 'Medium'
  }
]
```

**Comment by ardlank** [comment] 2024-01-25 00:02
@delfuego @khirasaki Have you tried to use hostconfig? The Mobile SDK will take the hostconfig's font and apply them.

See more here: https://learn.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config

**Comment by delfuego** [comment] 2024-01-25 00:09
@ardlank I'm confused — how would one use a hostconfig file to set how the MS Teams iOS client itself displays Adaptive Cards? That's the issue I'm having — that in the *Teams client itself*, there's a rendering bug or issue that causes text to be displayed in a serif font that's not like any other content. And I get how hostconfig files are able to help you set global rendering defaults if you build an app that includes MS's Adaptive Card renderer, but... in this case, I'm not, I'm using MS's own app. And I can't include a new hostconfig file that would in any way override it.

**Comment by ardlank** [comment] 2024-01-25 15:37
I see @delfuego. I thought you were trying to use the SDK for your own app.

@hggz can you see about this font issue in Teams? Maybe edit the iOS Team's hostconfig?

**Comment by hggz** [comment] 2024-02-08 23:24
This change needs to be done within the teams app since the font styles are being overwritten there. In the AdaptiveCards-SDK the font with the above example displays as expected. There's a solution in the works right now. For now, we'll be keeping this open for now to track until the issue is resolved.

**Comment by tim-tribble-ai** [comment] 2024-04-04 03:30
Is there any update on this issue?

**Comment by salils3211** [comment] 2024-04-05 04:27
is there any update on this issue.

**Comment by GabrielMedAlv** [comment] 2024-04-08 23:41
@tim-tribble-ai  @salils3211  Yes. @hggz  have been working on a fix for this on Teams side. This is the link of his PR. https://domoreexp.visualstudio.com/Teamspace/_git/Teamspace-iOS/pullrequest/953866

**Comment by tim-tribble-ai** [comment] 2024-04-08 23:50
Note: @GabrielMedAlv doesn't seem like that PR link is public. 

@hggz would you happen to have any timelines for when the fix will be rolled out? Thanks!

**Comment by paulsweston** [comment] 2024-05-29 07:41
Any update here? @hggz - much appreciated!

**Comment by GabrielMedAlv** [comment] 2024-07-03 22:19
Hello. A fix of this issue has been merged into Teams and will be in prod version soon. I will check the exact date of the new release.

**Closed** 2024-08-30 21:19 UTC
Labels: Bug, Area-Renderers
